codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "dist/**"
  - "build/**"
  - "public/**"
  - "tests/**"
